<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-RN5DS47J" ignored="2" name="Test" tests="5" failures="1" timestamp="2020-06-10T16:43:03 ICT" time="114.641" errors="0">
  <testcase name="invalidPassword" time="6.419" classname="com.qa.tests.LoginTest"/>
  <testcase name="invalidUsername" time="5.193" classname="com.qa.tests.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.random]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.random]
at com.qa.tests.LoginTest.invalidUsername(LoginTest.java:83)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- invalidUsername -->
  <testcase name="successfulLogin" time="6.265" classname="com.qa.tests.LoginTest"/>
  <testcase name="validateProductOnProductDetailsPage" time="8.969" classname="com.qa.tests.ProductTest"/>
  <testcase name="validateProductOnProductsPage" time="2.739" classname="com.qa.tests.ProductTest"/>
  <testcase name="@AfterTest afterTest" time="0.0" classname="com.qa.base.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase name="@BeforeTest beforeTest" time="0.0" classname="com.qa.base.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
</testsuite> <!-- Test -->
